{
 "title": "Cloud-Native Enterprise Infrastructure Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n1 -\r\n(\r\nnode_memory_MemAvailable_bytes\r\n/\r\nnode_memory_MemTotal_bytes\r\n)\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ( avg by(job)( rate(node_cpu_seconds_total{mode=\"idle\"}[5m]) ) * 100 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\r\n(\r\nnode_filesystem_avail_bytes{\r\nfstype!=\"tmpfs\",\r\nmountpoint=\"/\"\r\n}\r\n/\r\nnode_filesystem_size_bytes{\r\nfstype!=\"tmpfs\",\r\nmountpoint=\"/\"\r\n}\r\n*100\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|docker.*|veth.*\"}[5m])",
     "legendFormat": "{{job}} RX"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"web-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"log-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nginx-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Website",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Server Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reading Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Writing Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" }
   ]
  },
  { "title": "Centralized Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Live Docker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"}"
    }
   ]
  },
  {
   "title": "Docker Log Volume",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "logs" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Logs by Container",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(filename) (\r\n  count_over_time({job=\"docker\"}[5m])\r\n)"
    }
   ]
  },
  {
   "title": "Alerting Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}